[package]
name = "attestation_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
x509-parser = "0.15.0"
hex = "0.4.3"
base64 = "0.13.0"
serde_cbor = "0.11.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.6"
sha2 = "0.10.8"

